apiVersion: v1
kind: Pod
spec:
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "jenkins"
      effect: "NoSchedule"
  containers:
    - name: jdk
      image: openjdk:17-jdk-slim-buster
      command:
        - sleep
      args:
        - 9999999
      env:
        name: GRADLE_USER_HOME
        value: "/home/jenkins/agent/"
      volumeMounts:
        - name: jenkins-agent-data
          mountPath: /home/jenkins/agent/
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - sleep
      args:
        - 9999999
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
    - name: jenkins-agent-data
      persistentVolumeClaim:
        claimName: jenkins-agent-pvc
    - name: docker-config
      configMap:
        name: docker-config