apiVersion: v1
kind: Pod
spec:
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "jenkins"
      effect: "NoSchedule"
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.13.3-1-jdk17
      securityContext:
        runAsUser: 0
      env:
        - name: GRADLE_USER_HOME
          value: "/home/jenkins/agent/.gradle"
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - sleep
      args:
        - 9999999
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
    - name: docker-config
      configMap:
        name: docker-config