apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/managed-by: kubectl
  name: demo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy:
    rollingUpdate:
      maxSurge: 15%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: SPRING_PROFILES_ACTIVE
          image: DOCKER_IMAGE_PLACE_HOLDER:DOCKER_IMAGE_TAG_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          name: demo
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi